server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

logger:
  namespace: psc-statement-delta-consumer

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: ${PSC_STATEMENT_DELTA_LISTENER_CONCURRENCY:1}

psc-statement:
  delta:
    group-id: ${PSC_STATEMENT_DELTA_GROUP_ID:psc-statement-delta-consumer}
    topic: ${PSC_STATEMENT_DELTA_TOPIC:psc-statement-delta}
    retry-attempts: ${PSC_STATEMENT_DELTA_ATTEMPTS:4}
    backoff-delay: ${PSC_STATEMENT_DELTA_BACKOFF_DELAY:100}

api:
  psc-statements-data-api-key: ${PSC_STATEMENTS_DATA_API_KEY}
  api-url: ${API_URL:http://localhost:8888}
  internal-api-url: ${INTERNAL_API_URL:localhost}

encoding:
  salt: ${PSC_STATEMENT_SALT}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: psc-statement-delta-consumer/healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true